### ISSUE TITLE
TypeError: htmlToText.fromString is not a function

### ISSUE THREAD

**Issue by codebyankita** [html-to-text/node-html-to-text#309] opened 2023-12-05 09:30 UTC
```js
const htmlToText = require('html-to-text');
const mailOptions = {
      from: this.from,
      to: this.to,
      subject,
      html,
      text: htmlToText.fromString(html)
    };
```

```
**ERROR**
{TypeError: htmlToText.fromString is not a function
    at Email.send (C:\\Code\\Nodejs\\Natours App\\utils\\email.js:50:24)
    at Email.sendWelcome (C:\\Code\\Nodejs\\Natours App\\utils\\email.js:58:16)
    at C:\\Code\\Nodejs\\Natours App\\controllers\\authController.js:43:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by KillyMXI** [comment] 2023-12-05 11:17
~~Duplicate of #218~~

**Comment by KillyMXI** [comment] 2023-12-05 11:25
Actually, not a duplicate.
Read the documentation - your code is not compatible with the new version.

**Closed as completed by KillyMXI** 2023-12-05 11:25 UTC

**Comment by michelbaratella** [comment] 2024-07-30 19:31
@KillyMXI Can you elaborate on "not compatible"? I'm going through the same course Ankita was and got the same exact error.

**Comment by michelbaratella** [comment] 2024-07-30 19:34
Nevermind, just found this on the Q&A of the course:

I just want to update everyone on html-to-string's fromString method, it has been deprecated so it won't work if you use it.

Instead, import { htmToText } from 'html-to-text' then rather than using html.fromString()  use htmlToText() directly.

**Comment by KillyMXI** [comment] 2024-07-30 19:45
@michelbaratella can you please link to the course in a separate comment (and delete later), so I can also know who is behind this.

I'm glad they have it in Q&A, but it is annoying when they can't update the source of confusion itself.
`fromString()` was deprecated in version 6.0.0 (2020-10-31) and removed in version 9.0.0 (2022-12-03).

I can't keep up with Node.js updates myself, but I'm not trying to teach others.
They provide a course that was either created before 2020-10-31 and never revised properly, or later, and ignored the documentation of packages it suggests to inexperienced users...

**Comment by michelbaratella** [comment] 2024-07-30 19:52
It's a pretty big course (over 40 hours) and according to the platform it was updated the last time on November 2023: https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/

Also here's the instructor twitter (couldn't find his Github profile): https://x.com/jonasschmedtman

It's probably hard to keep up with changes on such a big course as well, anyways hope it helped!

**Comment by KillyMXI** [comment] 2024-07-30 20:52
> It's a pretty big course (over 40 hours) and according to the platform it was updated the last time on November 2023: REDACTED
> 
> Also here's the instructor twitter (couldn't find his Github profile): REDACTED
> 
> It's probably hard to keep up with changes on such a big course as well, anyways hope it helped!

Thank you.

In the course reviews, I can see that it is originally from 2019, and there are a lot of reports that many dependencies have changed, not just mine.

I guess the main issue with IT courses is that they get outdated quickly, and nobody wants to re-record videos again.
I found the instructor's GitHub profile, but I see no need to cast them here, for that reason.

This kind of passive income looks way too passive, to the point when it becomes scammy.
Deleting your comment with links, because I don't want to endorse their work in any way. (Unless they sponsor mine, haha)
