### ISSUE TITLE
How to avoid getting contents in <style> elements?

### ISSUE THREAD

**Issue by jasonsun001** [html-to-text/node-html-to-text#268] opened 2022-12-13 07:50 UTC
I need to get 'pure text' from a html page. However, I sometimes get styles or scripts. I tried this library. It's good, but still I got styles. Can I avoid it?

**Comment by KillyMXI** [comment] 2022-12-13 12:02
`html-to-text` is made to ignore `<style>` tags and I see no regression in tests.
You should've used the "Bug report" template to provide the reproduction so I could see what's wrong.

Now I have to ask you the same things:
- what version are you using;
- What options are you using;
- HTML fragment condensed to be smallest where the issue is still reproduced;
- Output you get;
- Expected output.

**Comment by KillyMXI** [comment] 2023-01-11 18:24
Closing this because got no follow up.
The issue was likely the same as #275.

**Closed by KillyMXI** 2023-01-11 18:24 UTC
