### ISSUE TITLE
preserveNewlines adds extraneous newlines when outside of some html elements

### ISSUE THREAD

**Issue by mdesson** [html-to-text/node-html-to-text#232] opened 2021-07-14 20:04 UTC
**Minimal HTML example**

```html
<p>top</p>\n<p>bottom</p>
```

**Options**

```javascript
{ preserveNewlines: true }
```

**Observed output**

```
top




bottom
```

**Expected output**

```
top


bottom
```

**Version information**

- html-to-text: 8.0.0 (bug introduced in 6.0.0)
- node: v12.13.1

----

With `preserveNewlines` set to `true`, if `\n` is not placed inside a `<p>` tag, two extra newlines will be added. However if it's placed inside a `<p>` tag, it will have the desired output. 

Note that I haven't tested this with other html tags.

On version 5.1.1, the output was:

```
top

bottom
```

**Comment by KillyMXI** [comment] 2021-07-14 20:41
You've opened two issues and then edited this one several times.
Which one I should keep? It's unclear to me which issue has the actually expected number of line breaks in the Expected output section.

**Comment by mdesson** [comment] 2021-07-14 20:55
I apologize for the confusion and spammed issues, not sure what happened on the duplicate issues.

For the edits, I wasn't totally sure what the expected output should be upon further reflection.

Basically I used this simple script to test:

```js
import  { fromString } from 'html-to-text'

const newlineOutside = '<p>top</p>\n<p>bottom</p>'
const newlineInside = '<p>top</p><p>\nbottom</p>'

const outputOutside = fromString(newlineOutside, {
		preserveNewlines: true,
});

const outputInside = fromString(newlineInside, {
		preserveNewlines: true,
});

console.log(outputOutside)
console.log('---')
console.log(outputInside)
```

On version 6.0.0^ it gives the output:

```
top




bottom
---
top


bottom
```

On version 5.1.1 it gives:

```
top

bottom
---
top

bottom
```

The edits were because while there seems to be an issue in 6.0.0^ I wasn't entirely sure what the desired behaviour should be. I personally prefer the 5.1.1 output, but in html there is typically a newline between paragraph tags, so the extra line actually makes sense.

In either case, the extra newlines when the `\n` is outside of the `p` tag is an unexpected behaviour. I'm just unsure if two newlines (like in 6.0.0) or one newline (like in 5.1.1) is the correct output.

I've edited the issue one last time, sorry again for the spammy edits and double issues. You can close out the other one.

**Comment by KillyMXI** [comment] 2021-07-14 21:32
Version 5.1.1 used very naive way to insert line breaks. It can't really be a reference point.
But we can paraphrase it: one option to consider might be to not preserve newlines in places where there are enough line breaks for other reasons.

Version 6.0.0 ensures there are at least 2 line breaks (one empty line) before and after a paragraph. But newlines from the input html are not really considered as whitespace characters when you set `preserveNewlines` to `true`.

Newline inside a paragraph directly translates into a line break in the output text, not affecting any other logic, and two line breaks are inserted between paragraphs (total 3 line breaks or 2 empty lines).

Line break between paragraphs currently acts kinda like a non-whitespace text node. This resulted in 2 line breaks after a paragraph, one line break preserved, then 2 more line breaks before next paragraph (total 5 line breaks or 4 empty lines).

I agree, this is an undesirable behavior. I'll think how to make it produce equal output regardless of the newline position.

`br` tag in the input results in 3 line breaks (2 empty lines) in either position. I'll consider achieving the equivalent behavior as another possible target.

```js
const brOutside = '<p>top</p><br/><p>bottom</p>';
const brInside = '<p>top</p><p><br/>bottom</p>';
```

I'm not sure currently how much of a breaking change this will be and so when I can ship the fix.

**Comment by mdesson** [comment] 2021-07-15 17:52
That makes a lot of sense, thanks for the explanation. No worries on the timeline, I can try to work around it in the meantime with a temporary solution.

**Comment by KillyMXI** [comment] 2021-11-07 17:49
Fixed in version 8.1.0.

If nothing but newlines has to be added then it is handled as a special case, effectively adding to trailing/leading linebreak numbers without disrupting them.
Behavior is consistent with `<br/>` tags.

**Closed by KillyMXI** 2021-11-07 17:49 UTC

**Comment by goamn** [comment] 2022-12-08 08:54
I had a chance to test out version 9.0.2. It is still adding extraneous newlines (double new lines instead of just the one).

**Comment by KillyMXI** [comment] 2022-12-08 11:15
@goamn I would need a minimal example where it happens for you.
Also make sure you are running what you think you do.

I see no regression in tests I previously written for this issue.
So, it is either some other corner case I'm unaware of, a usage mistake or even an intended behavior on poorly formatted input.
I can't tell without more info.
